<?php

namespace AnalyzerBundle\Repository;

/**
 * BankEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
