<?php

namespace AnalyzerBundle\Repository;

/**
 * BankTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
