<?php

namespace AnalyzerBundle\Repository;

/**
 * LoanTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
